### ISSUE TITLE
Softbutton.isHighlighted doesn't work

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/generic_hmi#183] opened 2019-07-23 19:42 UTC
When a `SoftButton` RPC is sent with `isHighlighted` set to `true`, The generic HMI doesn't highlight the button as it is supposed to.

**Comment by jacobkeeler** [comment] 2020-03-25 13:39
Duplicate of #135

**Closed by jacobkeeler** 2020-03-25 13:39 UTC
