### ISSUE TITLE
Only part of the text in a soft button that supports both text and images is shown.

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/generic_hmi#242] opened 2020-02-28 20:11 UTC
# Bug Report
Only part of the text in a soft button that supports both text and images is shown.

1. Create an app with `appType` of `COMMUNICATION` and a main screen template of `GRAPHIC_WITH_TEXTBUTTONS`.
1. Create 4 soft buttons that support both text and images. 
1. Display the soft buttons using a `Show` request.

### Expected result
All the soft buttons show both the image and the text.

### Actual result
Only a sliver of the text is shown to the left of the button. In the screenshot, the top left soft button is supposed to show "Call" under the image. The highlighted box shows that you can only see part of the "C". You can see part of the text on the left side of each button. 

![Generic_HMI_text_and_image_soft_button_bug_day_mode](https://user-images.githubusercontent.com/19915981/75583835-6e1aa900-5a3c-11ea-8f5f-eeffe209320e.png)

### More Information
**Bug seen on:**  Manticore (SDL Core v6.0.1 and Generic HMI v0.7.2.) and the develop branch of Generic_HMI (commit 0ae8e3ea6d475651a83ff44da23f1d434b4266e7)
**Bug seen on web browsers:** Safari, Chrome, and Chromium

**Comment by JackLivio** [comment] 2020-03-02 20:37
@JackLivio

**Comment by iCollin** [comment] 2020-03-31 20:59
Hello @NicoleYarroch,

I failed to reproduce this issue. Could you show me the exact structure of the RPC you sent or give me any other additional info that might help me reproduce this bug?

Thank you!

<img width="973" alt="Screen Shot 2020-03-31 at 4 50 39 PM" src="https://user-images.githubusercontent.com/12716076/78074545-e8f31e80-7370-11ea-8b39-ba5a6029732a.png">

**Comment by NicoleYarroch** [comment] 2020-04-01 17:43
@iCollin Are you using static icons in your buttons? If i use static icons, things look correct. However, if I use a custom image in the soft button, I still see the bug.

**Comment by iCollin** [comment] 2020-04-02 17:49
I tried with dynamic images as well and still couldn't reproduce :grimacing:. Could you maybe send me a patch for the iOS example app so I could use your code exactly?

![Screen Shot 2020-04-02 at 1 47 47 PM](https://user-images.githubusercontent.com/12716076/78281514-ca179800-74e8-11ea-82b3-a238e384c19b.png)

![Screen Shot 2020-04-02 at 1 47 28 PM](https://user-images.githubusercontent.com/12716076/78281510-c84dd480-74e8-11ea-901e-63620415bd25.png)

**Comment by ShobhitAd** [comment] 2020-04-20 19:13
Closed via https://github.com/smartdevicelink/generic_hmi/pull/254

**Closed by ShobhitAd** 2020-04-20 19:13 UTC
